# Form implementation generated from reading ui file 'view/add_order_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddOrderWindow(object):
    def setupUi(self, AddOrderWindow):
        AddOrderWindow.setObjectName("AddOrderWindow")
        AddOrderWindow.resize(700, 600)
        AddOrderWindow.setMinimumSize(QtCore.QSize(700, 600))
        AddOrderWindow.setStyleSheet("QWidget{background-color: #FFFFFF; font-family: \"Times New Roman\"; font-size: 13pt; color: black} QLineEdit{border: 1px solid black;} QPushButton{background-color: #00FA9A} QComboBox{border: 1px solid black;}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddOrderWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_back_btn = QtWidgets.QPushButton(parent=AddOrderWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.verticalLayout.addWidget(self.go_back_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.status_cbx = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.status_cbx.setObjectName("status_cbx")
        self.verticalLayout.addWidget(self.status_cbx)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pick_up_point_cbx = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.pick_up_point_cbx.setObjectName("pick_up_point_cbx")
        self.verticalLayout.addWidget(self.pick_up_point_cbx)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(parent=AddOrderWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.date_order_de = QtWidgets.QDateEdit(parent=AddOrderWindow)
        self.date_order_de.setCalendarPopup(True)
        self.date_order_de.setDate(QtCore.QDate(2026, 6, 11))
        self.date_order_de.setObjectName("date_order_de")
        self.verticalLayout.addWidget(self.date_order_de)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(parent=AddOrderWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dat_delivery_de = QtWidgets.QDateEdit(parent=AddOrderWindow)
        self.dat_delivery_de.setCalendarPopup(True)
        self.dat_delivery_de.setDate(QtCore.QDate(2026, 6, 11))
        self.dat_delivery_de.setObjectName("dat_delivery_de")
        self.verticalLayout.addWidget(self.dat_delivery_de)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.add_order_btn = QtWidgets.QPushButton(parent=AddOrderWindow)
        self.add_order_btn.setObjectName("add_order_btn")
        self.verticalLayout.addWidget(self.add_order_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AddOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(AddOrderWindow)

    def retranslateUi(self, AddOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        AddOrderWindow.setWindowTitle(_translate("AddOrderWindow", "Добавление заказа"))
        self.go_back_btn.setText(_translate("AddOrderWindow", "Назад"))
        self.label.setText(_translate("AddOrderWindow", "Дата Заказа"))
        self.label_2.setText(_translate("AddOrderWindow", "Дата Доставки"))
        self.add_order_btn.setText(_translate("AddOrderWindow", "Добавить Заказ"))
