# Form implementation generated from reading ui file 'auth_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindow(object):
    def setupUi(self, AuthorizationWindow):
        AuthorizationWindow.setObjectName("AuthorizationWindow")
        AuthorizationWindow.resize(521, 386)
        AuthorizationWindow.setMinimumSize(QtCore.QSize(450, 350))
        AuthorizationWindow.setStyleSheet("QWidget{background-color: #FFFFFF; font: 13pt \"Times New Roman\"; color: black} QLineEdit{border: 1px solid black;} QPushButton{background-color: #00FA9A}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthorizationWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_le = QtWidgets.QLineEdit(parent=AuthorizationWindow)
        self.login_le.setObjectName("login_le")
        self.verticalLayout.addWidget(self.login_le)
        self.password_le = QtWidgets.QLineEdit(parent=AuthorizationWindow)
        self.password_le.setObjectName("password_le")
        self.verticalLayout.addWidget(self.password_le)
        self.auth_btn = QtWidgets.QPushButton(parent=AuthorizationWindow)
        self.auth_btn.setObjectName("auth_btn")
        self.verticalLayout.addWidget(self.auth_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.guest_btn = QtWidgets.QPushButton(parent=AuthorizationWindow)
        self.guest_btn.setObjectName("guest_btn")
        self.verticalLayout.addWidget(self.guest_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(AuthorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindow)

    def retranslateUi(self, AuthorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindow.setWindowTitle(_translate("AuthorizationWindow", "Окно авторизации"))
        self.login_le.setPlaceholderText(_translate("AuthorizationWindow", "Введите логин"))
        self.password_le.setPlaceholderText(_translate("AuthorizationWindow", "Введите пароль"))
        self.auth_btn.setText(_translate("AuthorizationWindow", "Войти"))
        self.guest_btn.setText(_translate("AuthorizationWindow", "Войти как гость"))
