# Form implementation generated from reading ui file 'view/orders_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrdersWindow(object):
    def setupUi(self, OrdersWindow):
        OrdersWindow.setObjectName("OrdersWindow")
        OrdersWindow.resize(745, 620)
        OrdersWindow.setMinimumSize(QtCore.QSize(700, 600))
        OrdersWindow.setStyleSheet("QWidget{background-color: #FFFFFF; font-family: \"Times New Roman\"; font-size: 13pt; color: black} QLineEdit{border: 1px solid black;} QPushButton{background-color: #00FA9A} QComboBox{border: 1px solid black;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(OrdersWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.go_back_btn = QtWidgets.QPushButton(parent=OrdersWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.gridLayout.addWidget(self.go_back_btn, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.open_add_order_window_btn = QtWidgets.QPushButton(parent=OrdersWindow)
        self.open_add_order_window_btn.setObjectName("open_add_order_window_btn")
        self.gridLayout.addWidget(self.open_add_order_window_btn, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=OrdersWindow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 721, 553))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(OrdersWindow)
        QtCore.QMetaObject.connectSlotsByName(OrdersWindow)

    def retranslateUi(self, OrdersWindow):
        _translate = QtCore.QCoreApplication.translate
        OrdersWindow.setWindowTitle(_translate("OrdersWindow", "Cписок заказов"))
        self.go_back_btn.setText(_translate("OrdersWindow", "Назад"))
        self.open_add_order_window_btn.setText(_translate("OrdersWindow", "Добавить заказ"))
