# Form implementation generated from reading ui file 'view/products_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductsWindow(object):
    def setupUi(self, ProductsWindow):
        ProductsWindow.setObjectName("ProductsWindow")
        ProductsWindow.resize(747, 600)
        ProductsWindow.setMinimumSize(QtCore.QSize(700, 600))
        ProductsWindow.setStyleSheet("QWidget{background-color: #FFFFFF; font-family: \"Times New Roman\"; font-size: 13pt; color: black} QLineEdit{border: 1px solid black;} QPushButton{background-color: #00FA9A} QComboBox{border: 1px solid black;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_I = QtWidgets.QLabel(parent=ProductsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_I.sizePolicy().hasHeightForWidth())
        self.logo_I.setSizePolicy(sizePolicy)
        self.logo_I.setMaximumSize(QtCore.QSize(30, 30))
        self.logo_I.setText("")
        self.logo_I.setScaledContents(True)
        self.logo_I.setObjectName("logo_I")
        self.verticalLayout.addWidget(self.logo_I, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.user_name_I = QtWidgets.QLabel(parent=ProductsWindow)
        self.user_name_I.setText("")
        self.user_name_I.setObjectName("user_name_I")
        self.verticalLayout.addWidget(self.user_name_I)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.go_back_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.gridLayout.addWidget(self.go_back_btn, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.sort_cbx = QtWidgets.QComboBox(parent=ProductsWindow)
        self.sort_cbx.setObjectName("sort_cbx")
        self.gridLayout.addWidget(self.sort_cbx, 1, 1, 1, 1)
        self.search_le = QtWidgets.QLineEdit(parent=ProductsWindow)
        self.search_le.setObjectName("search_le")
        self.gridLayout.addWidget(self.search_le, 1, 3, 1, 1)
        self.filter_cbx = QtWidgets.QComboBox(parent=ProductsWindow)
        self.filter_cbx.setObjectName("filter_cbx")
        self.gridLayout.addWidget(self.filter_cbx, 1, 0, 1, 1)
        self.add_product_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        self.add_product_btn.setObjectName("add_product_btn")
        self.gridLayout.addWidget(self.add_product_btn, 0, 1, 1, 1)
        self.open_orders_window_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        self.open_orders_window_btn.setObjectName("open_orders_window_btn")
        self.gridLayout.addWidget(self.open_orders_window_btn, 0, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=ProductsWindow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 723, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ProductsWindow)
        QtCore.QMetaObject.connectSlotsByName(ProductsWindow)

    def retranslateUi(self, ProductsWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductsWindow.setWindowTitle(_translate("ProductsWindow", "Cписок товаров"))
        self.go_back_btn.setText(_translate("ProductsWindow", "Выйти"))
        self.search_le.setPlaceholderText(_translate("ProductsWindow", "Поиск"))
        self.add_product_btn.setText(_translate("ProductsWindow", "Добавить"))
        self.open_orders_window_btn.setText(_translate("ProductsWindow", "Заказы"))
